[env]
CARGO_REGISTRY_DEFAULT = "rsproxy"

# LOG: trace, debug, info, warn, error
DEFMT_LOG             = "trace"
DEFMT_RTT_BUFFER_SIZE = "1024"

PROBE_RS_CHIP     = "STM32F103C8"
PROBE_RS_PROTOCOL = "swd"

[alias]
rr = "run --release"
br = "build --release"


[build]
target = "thumbv7m-none-eabi"
rustflags = [
    "-Clinker-plugin-lto",
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=--nmagic",
    "-Clink-arg=-Tdefmt.x",
    # "-Cforce-frame-pointers",
    # "-Zmacro-backtrace",
]

[target.thumbv7m-none-eabi]
# linker = "rust-lld"
runner = [
    "probe-rs",
    "run",
    "--preverify",
    "--no-location",
    # "--verify",
    # "--connect-under-reset",
    # "--log-format",
    # "{L} {s}",
]
